name: "Terraform"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  PROXMOX_API_URL: ${{ secrets.PROXMOX_API_URL }}
  PROXMOX_API_TOKEN_ID: ${{ secrets.PROXMOX_API_TOKEN_ID }}
  PROXMOX_API_TOKEN_SECRET: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}

jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted
    environment: "Actions"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Terraform Format"
        id: fmt
        run: terragrunt fmt --terragrunt-log-level debug --terragrunt-non-interactive
        continue-on-error: true

      - name: "Terraform Init"
        id: init
        env:
          PROXMOX_API_URL: ${{ env.PROXMOX_API_URL }}
          PROXMOX_API_TOKEN_ID: ${{ env.PROXMOX_API_TOKEN_ID }}
          PROXMOX_API_TOKEN_SECRET: ${{ env.PROXMOX_API_TOKEN_SECRET }}
        run: terragrunt run-all init -backend-config="token=${{ secrets.TF_TOKEN }}" -lock=false --terragrunt-log-level debug --terragrunt-non-interactive
        continue-on-error: false

      - name: "Terraform Validate"
        id: validate
        env:
          PROXMOX_API_URL: ${{ env.PROXMOX_API_URL }}
          PROXMOX_API_TOKEN_ID: ${{ env.PROXMOX_API_TOKEN_ID }}
          PROXMOX_API_TOKEN_SECRET: ${{ env.PROXMOX_API_TOKEN_SECRET }}
        run: terragrunt run-all validate --terragrunt-log-level debug --terragrunt-non-interactive
        continue-on-error: false

      - name: "Terraform Plan"
        id: plan
        env:
          PROXMOX_API_URL: ${{ env.PROXMOX_API_URL }}
          PROXMOX_API_TOKEN_ID: ${{ env.PROXMOX_API_TOKEN_ID }}
          PROXMOX_API_TOKEN_SECRET: ${{ env.PROXMOX_API_TOKEN_SECRET }}
        if: github.event_name == 'pull_request'
        run: terragrunt run-all plan -lock=false --terragrunt-log-level debug --terragrunt-non-interactive
        continue-on-error: false

      - name: "Terraform Apply"
        id: apply
        env:
          PROXMOX_API_URL: ${{ env.PROXMOX_API_URL }}
          PROXMOX_API_TOKEN_ID: ${{ env.PROXMOX_API_TOKEN_ID }}
          PROXMOX_API_TOKEN_SECRET: ${{ env.PROXMOX_API_TOKEN_SECRET }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terragrunt run-all apply -lock=false --terragrunt-log-level debug --terragrunt-non-interactive
        continue-on-error: true

      - name: "Terraform Output"
        id: output
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terragrunt run-all output --terragrunt-log-level debug --terragrunt-non-interactive
        continue-on-error: false
